spring.application.name=private-cloud-storage
spring.datasource.url=jdbc:h2:mem:cloudstorage
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true